config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]

  resources :products do
    resources :comments, only: [:create]
    resource :vote, only: [:create, :destroy]
  end
  
  
  
  #get '/products', to: 'products#index'
  #get '/products/new', to: 'products#new', as: 'new_product'
  #post '/products', to: 'products#create'
  #get '/products/:id', to: 'products#show', as: 'product'
  #get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  #patch '/products/:id', to: 'products#update'
  #delete '/products/:id', to: 'products#destroy'

  #resources :products, only [:acciones-que-queremos-que-muestre :show :edit]
  #resources :products, except [:acciones-que-queremos-que-excluya :index :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  product_id :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(50)
#  url         :string(50)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Product < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_many :votes
	validates :name, presence: true
	validates :url, presence: true
	has_one_attached :image

	validate :image_format

	def image_format
      if image.attached?
      if image.blob.byte_size > 1000000
        image.purge_later
        errors[:base] << 'Too big'
      elsif !image.blob.content_type.starts_with?('image/')
        image.purge_later
        errors[:base] << 'Wrong format'
      end
    end
 end

	def voted_by?(user)
		votes.exists?(user: user)
	end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(100)
#  password_digest :string
#  name            :string(100)
#  twitter_handle  :string(50)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    has_many :comments
    has_many :products
    has_many :votes

	validates :email, uniqueness: true, format: { with: /@/,
    message: "Debe contener un arroba" }
	validates :password_digest, presence: true, on: :create
	validates :password_digest, length: { in: 6..20 }, allow_nil: true
	validates :name, presence: true

	has_secure_password
	has_secure_password validation: false

end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  product_id :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vote < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def sign_in(user)
  cookies.permanent.signed[:user_id] = user.id
  @current_user = user
end

def sign_out
  cookies.delete(:user_id)
  @current_user = nil
end

private
  def signed_in?
    !current_user.nil?
  end
  helper_method :signed_in?

  def current_user
    @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
  rescue ActiveRecord::RecordNotFound
  end
  helper_method :current_user
  
  def private_access
  redirect_to :login unless signed_in?
  end
   
  def public_access
  redirect_to root_path if signed_in?
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		product = Product.find(params[:product_id])
		product.comments.create(comments_params)

		redirect_to product
		#manda a detalles del producto
	end

	private
	def comments_params
		params.require(:comment).permit(:body).merge(user: current_user)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :private_access, except: [:index, :show]


	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end
    
	def create
		@product = Product.new(product_params)
		@product.user = current_user
		if @product.save
			redirect_to products_path, notice: "El producto fue publicado con exito"
		else
		    render :new
		end
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		product = Product.find(params[:id])
		if product.update(product_params)
		redirect_to products_path, notice: "El producto a sido modificado con exito"
	    else
        render :edit   
	    end
	end

	def destroy
		product = Product.find(params[:id])
		product.destroy

		redirect_to products_path, notice: "El producto fue eliminado con exito"
	end

	private
  
	def product_params
		params.require(:product).permit(:name, :url, :description, :image)
	end
end	

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :private_access, only: [:destroy]
	before_action :public_access, except: [:destroy]

	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			sign_in(user)
			redirect_to root_path
		else
			render :new
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
  @user = User.new(user_params)
  if @user.save
    redirect_to root_path
  else
    render :new
  end
end

private
  def user_params
    params.require(:user).permit(:email, :password, :name, :twitter_handle)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
		product = Product.find(params[:product_id])
		product.votes.create(user: current_user)

		redirect_to root_path
	end

	def destroy
		product = Product.find(params[:product_id])
		product.votes.where(user: current_user).take.try(:destroy)

		redirect_to root_path
	end

	#product.votes.where(user: current_user).take.try(:destroy) , 
	#lo que hace es al devolver un array la sentencia product.votes.where(user: current_user), 
	#take toma el primer elemento y try verifica que ese elemento no sea nil 
    #para que la aplicación no se muera.
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def form_title
	@product.new_record? ? "Publicar Producto" : "Modificar Producto"
  end
  
  def header_style
  if @product.image.attached?
    %{ style="background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('#{rails_blob_url(@product.image)}'); background-size: cover; background-position: center;" }.html_safe
  else
    ""
  end
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Producthunt</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Product Hunt", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">    
        <ul class="navbar-nav ml-auto">
          <% if signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle avatar" data-toggle="dropdown">
              <img src="<%= Gravatar.new("#{current_user.email}").image_url %>" class="img-circle" />
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Nuevo Producto", new_product_path %></li>
              <li><%= link_to "Salir", logout_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Regístrate", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <% if flash[:notice] %>
  <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>


  <%= yield %>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/18c2d51a46.js"></script>
</body>
</html>

app/views/products/_form.html.erb
   	<div class="container">
   		<div class="row">
   			<div class="col-sm-6 offset-sm-3">
   				<h1><%= form_title %></h1>
           <% if @product.errors.any? %>
           <div class="alert alert-danger">
             <ul>
              <% @product.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <%= form_for @product do |f| %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control input-lg", placeholder: "ingresa el nombre del producto" %>
          </div>
          <div class="form-group">
            <%= f.url_field :url, class: "form-control input-lg", placeholder: "ingresa la URL del producto" %>
          </div>
          <div class="form-group">
            <%= f.text_area :description, class: "form-control input-lg", placeholder: "ingresa la descripcion del producto" %>
          </div>
          <div class="form-group">
            <%= f.file_field :image %>
          </div>
          <div>
            <%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">

      <div class="products">
        <% @products.each do |product| %>
        <div class="product clearfix">
          <% if product.voted_by? current_user %>
          <%= link_to product_vote_path(product), method: :delete, class: "product-upvote upvote-active" do %>
          <span class="upvote-arrow"></span>
          <span class="upvote-count"><%= product.votes.count %></span>
          <% end %>
          <% else %>
          <%= link_to product_vote_path(product), method: :post, class: "product-upvote" do %>
          <span class="upvote-arrow"></span>
          <span class="upvote-count"><%= product.votes.count %></span>
          <% end %>
          <% end %>
          <% if product.image.attached? %>
          <div class="product-img">
            <%= image_tag product.image.variant(resize: '100x100') %>
          </div>
          <% end %>
          <div class="product-details">
            <span class="product-title"><%= link_to product.name, product %></span>
            <span class="product-description"><%= product.description %></span>
          </div>
          <div class="product-comments">
            <span class="glyphicon glyphicon-comment"></span>
            <span class="comment-count"><%= product.comments.count %></span>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="product-page">
  <header class="product-header" <%= header_style %>>
    <h1><%= @product.name %></h1>
    <p><%= @product.description %></p>
    <a href="<%= @product.url %>" class="btn btn-primary btn-lg" target="_blank">¡Obtenlo!</a>
    <% if signed_in? && @product.user == current_user %>
    <div class="actions">
      <%= link_to "<span class='fas fa-edit'></span>".html_safe, edit_product_path(@product) %>
      <%= link_to "<span class='fas fa-trash-alt'></span>".html_safe, @product, method: :delete, data: { confirm: "¿Estás seguro de eliminar este producto?" } %>
    </div>
    <% end %>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="votes">
          <h2>Votos</h2>
          <% @product.votes.each do |vote| %>
          <img src="<%= Gravatar.new("#{vote.user.email}").image_url %>" class="img-circle" />
          <% end %>
        </div>

        <div class="comments">
          <h2>Comentarios</h2>
          <% @product.comments.each do |comment| %>
          <div class="panel panel-default">
            <header class="panel-heading"><img src="<%= Gravatar.new("#{comment.user.email}").image_url %>" class="img-circle" /> <%= comment.user.name %></header>
            <div class="panel-body"><%= comment.body %></div>
          </div>
          <% end %>

          <% if signed_in? %>
          <%= form_for [@product, @product.comments.build] do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "Agregar comentario" %>
          </div>

          <div class="actions text-right">
            <%= f.submit "Comentar", class: "btn btn-primary" %>
          </div>
          <% end %>
          <% end %>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Crear Cuenta</h1>
         <% if @user.errors.any? %>
               <div class="alert alert-danger">
                 <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                 </ul>
              </div>
              <% end %>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control input-lg", placeholder: "Contraseña" %>
        </div>

        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre" %>
        </div>

        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="basic-addon1">@</span>
          <%= f.text_field :twitter_handle, class: "form-control input-lg", placeholder: "Twitter" %>
        </div>

        <div class="actions">
          <%= f.submit class: "btn btn-primary btn-block btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>